### ISSUE TITLE
[Bug] data-class=""  causes the compiler to break unfortunately

### ISSUE THREAD

**Issue by Intrflex** [JuniorTour/vue-template-babel-compiler#34]
Minor bug When and div has a data attribute like data-class the compiler can not compile and reports unexpected token :(

`   <li>
          <a
            class="btn js-waves-off"
            data-action="toggle"
            data-class="nav-function-fixed"
            href="#"
            title="Lock Navigation">
            <i class="ni ni-lock-nav" />
          </a>
        </li>`

**Comment by Intrflex** [comment]
Further testing actually shows its not the data-class.. its the fact i have function inside the class

**Comment by JuniorTour** [comment]
This is a bug.

Thanks for your feedback.

<hr />

It is caused by use `.split('function')` for split render function as string:
https://github.com/JuniorTour/vue-template-babel-compiler/blob/cb23dc9c4df0a8b974129f9faece15550024477f/src/templateCompiler.js#L25

So the `staticRenderFns`:
``` js
var staticRenderFns = [function () {
  var _vm=this;
  var _h=_vm.$createElement;
  var _c=_vm._self._c||_h;

  return _c('div', {
    attrs: {
      "id": "app"
    }
  }, [_c('a', {
    attrs: {
      "attr": "function"
    }
  }, [_vm._v("1")])]);
}];
```

will be split **wrongly** by `getArrayItems(compiledStaticRenders)` into:
![image](https://user-images.githubusercontent.com/14243906/151973261-35d25d5e-9fc3-45bf-93ac-9736914e48bb.png)

<hr />

Maybe we can use a more accurate Regular expression to parse render function?

Welcome for Pull Request!

**Comment by JuniorTour** [comment]
@Intrflex We have fixed this issue!

You can try it by run:
`npm install vue-template-babel-compiler@latest`

Thanks for your feedback again!
